[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]] # Include nativefs module
[patches.module]
source = 'nativefs.lua'
before = 'main.lua'
name = 'nativefs'

[[patches]] # Patch GreenNeedle loader to main
[patches.copy]
target = "main.lua"
position = "append"
sources = ["GreenNeedle.lua"]

[[patches]] # Initialize GreenNeedle after profile is loaded
[patches.pattern]
target = "game.lua"
pattern = "self:load_profile(G.SETTINGS.profile or 1)"
position = "after"
payload = "initGreenNeedle()"
match_indent = true
overwrite = false

[[patches]] # Inject key press handler
[patches.pattern]
target = "engine/controller.lua"
pattern = "if self.text_input_hook then"
position = "before"
payload = "GreenNeedle.key_press_update(key)"
match_indent = true
overwrite = false

[[patches]] # Inject key release handler
[patches.pattern]
target = "engine/controller.lua"
pattern = "if key == 'tab' and G.debug_tools then"
position = "before"
payload = "GreenNeedle.key_release_update(key)"
match_indent = true
overwrite = false

[[patches]] # Create Green Needle button on main menu
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local settings = UIBox_button({button = 'settings', label = {localize('b_settings')}, minw = 5, focus_args = {snap_to = true}})"
position = "after"
payload = "local greenneedle_settings = UIBox_button({button = 'greenneedle_config', label = {'Green Needle'}, colour = darken(G.C.GREEN, 0.25), shadow = true, text_colour = G.C.WHITE, minw = 5, focus_args = {snap_to = true}})"
match_indent = true

[[patches]] # Add Green Needle button to main options menu
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local t = create_UIBox_generic_options({ contents = {"
position = "after"
payload = "greenneedle_settings,"
match_indent = true

[[patches]] # Update loop
[patches.pattern]
target = "game.lua"
pattern = "G.FRAMES.MOVE = G.FRAMES.MOVE + 1"
position = "before"
payload = '''
GreenNeedle.update(dt)
'''
match_indent = true
overwrite = false
